eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true


server:
  port: 20261
spring:
  application:
    name: customer
  profiles:
    active: dev
  config:
    import: optional:configserver:http//localhost:8888