eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: git,vault #native
  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: myroot
          kv-version: 2
          backend: secret
          profile-separator: /
        git:
          uri: ${GL_URI}
          username: ${GL_USER}
          password: ${GL_TOKEN}
          default-label: main
          search-paths: "/**"
        native:
          search-locations:
            - file:D:\ISTAD-ITP\itp-micro\itp-config-repo\
            - file:D:\ISTAD-ITP\itp-micro\itp-config-repo\{application}\

